---
- name: Create mysql database
  become: yes
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  become: yes
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL